/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : KB1.c
**     Project     : carrito_com_def
**     Processor   : MCF51AC256ACLK
**     Component   : KBI
**     Version     : Component 01.096, Driver 01.25, CPU db: 3.00.065
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2015-05-25, 02:13, # CodeGen: 89
**     Abstract    :
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
**     Settings    :
**         Keyboard                    : KBI 
**         Used pins           
**         Pin 0                       : PTG0_KBI1P0
**         Pin 1                       : PTG2_KBI1P2
**         Pin 2                       : PTG1_KBI1P1
**         Pin 3                       : PTD2_KBI1P5_AD1P10_ACMP1O
**         Pin 4                       : PTD3_KBI1P6_AD1P11
**         Pin 5                       : PTG3_KBI1P3_AD1P18
**         Pin 6                       : PTG4_KBI1P4_AD1P19
**         Pin 7                       : PTD7_KBI1P7_AD1P15
**         Pull resistor               : up
**         Generate interrupt on       : falling
**         Interrupt service           : Enabled
**         Interrupt                   : Vkeyboard
**         Interrupt Priority          : 240
**         Enable in init. code        : Yes
**         Events enabled in init.     : Yes
**     Contents    :
**         GetVal  - byte KB1_GetVal(void);
**         SetEdge - byte KB1_SetEdge(byte edge);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file KB1.c
** @version 01.25
** @brief
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
*/         
/*!
**  @addtogroup KB1_module KB1 module documentation
**  @{
*/         

/* MODULE KB1. */

#include "Events.h"
#include "KB1.h"



/*
** ===================================================================
**     Event       :  KB1_OnInterrupt (module Events)
**
**     Component   :  KB1 [KBI]
**     Description :
**         This event is called when the active signal edge/level
**         occurs. This event is enabled only if <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
ISR(KB1_Interrupt)
{
  KBISC_KBACK = 0x01U;                 /* Clear the interrupt flag */
  KB1_OnInterrupt();                   /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  KB1_GetVal (component KBI)
**     Description :
**         Returns the value of pins
**     Parameters  : None
**     Returns     :
**         ---             - The value of associated pins (bits ordered
**                           according to the component list of pins)
** ===================================================================
*/
byte KB1_GetVal(void)
{
  byte value = 0x00U;
  value |= PTGD & 0x01U;
  value |= ((PTGD & 0x04U) >> 1);
  value |= (byte)((PTGD & 0x02U) << 1);
  value |= (byte)((PTDD & 0x04U) << 1);
  value |= (byte)((PTDD & 0x08U) << 1);
  value |= (byte)((PTGD & 0x08U) << 2);
  value |= (byte)((PTGD & 0x10U) << 2);
  value |= PTDD & 0x80U;
  return value;
}

/*
** ===================================================================
**     Method      :  KB1_SetEdge (component KBI)
**     Description :
**         Sets the sensitive edge. If all selected pins don't have the
**         same edge setting possibility, the method allows to set only
**         those edges that are common (possible to set for all
**         selected pins).
**     Parameters  :
**         NAME            - DESCRIPTION
**         edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
** ===================================================================
*/
byte KB1_SetEdge(byte edge)
{
  if ((edge != 0U) && (edge != 3U)) {  /* If parameter is out of range */
    return ERR_RANGE;                  /* ....then return error */
  }
  KBISC_KBIE = 0U;                     /* Disable device */
  if (edge == 0U) {
    KBISC_KBIMOD = 0U;                 /* Set the falling edge */
    /* KBISC: KBEDG7=0,KBEDG6=0,KBEDG5=0,KBEDG4=0 */
    KBISC &= (byte)(~(byte)0xF0U);
  }
  else {
    KBISC_KBIMOD = 0x01U;              /* Set the low level */
    /* KBISC: KBEDG7=0,KBEDG6=0,KBEDG5=0,KBEDG4=0 */
    KBISC &= (byte)(~(byte)0xF0U);
  }
  KBISC_KBACK = 0x01U;                 /* Clear the interrupt flag */
  KBISC_KBIE = 0x01U;                  /* Enable device */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  KB1_Init (component KBI)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void KB1_Init(void)
{
  /* KBISC: KBEDG7=0,KBEDG6=0,KBEDG5=0,KBEDG4=0,KBF=0,KBACK=0,KBIE=0,KBIMOD=0 */
  setReg8(KBISC, 0x00U);                
  /* KBIPE: KBIPE7=1,KBIPE6=1,KBIPE5=1,KBIPE4=1,KBIPE3=1,KBIPE2=1,KBIPE1=1,KBIPE0=1 */
  setReg8(KBIPE, 0xFFU);               /* Enable appropriate interrupt pin(s) */ 
  /* KBISC: KBACK=1 */
  setReg8Bits(KBISC, 0x04U);           /* Clear the interrupt flag */ 
  /* KBISC: KBIE=1 */
  setReg8Bits(KBISC, 0x02U);           /* Enable interrupts */ 
}

/* END KB1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
